import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

// My imports
import { Providers } from "./providers";

// Nav bars for desktop and mobile
import PrimaryNavbar from "./components/navbar/primaryNavbar/primaryNavbar";
import MobileNavBar from "./components/navbar/mobileNavbar/mobileNavBar";

// For globally shared currencies
import { GlobalContextProvider } from "./context/store";

const spaceGroteskFont = Space_Grotesk({
  subsets: ["latin"],
});

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGroteskFont.className}`}>
        <GlobalContextProvider>
          <Providers>
            <PrimaryNavbar />
            <MobileNavBar />
            <div className="flex items-center justify-center border-2 border-lime-300 bg-white-muted bg-no-repeat dark:bg-main-dark-purple">
              <div className="h-screen w-11/12 max-w-screen-xl flex-col items-center justify-start border-2 border-white">
                {children}
                {/* <Link href="/home">Home</Link>
                  <br />
                  <Link href="/portfolio">Portfolio</Link>
                  <br />
                  <Link href="/converter">Converter</Link> */}
              </div>
            </div>
            {/* Add the nav bar for mobile devices, no need to remove
                the <PrimaryNavbar /> that is located above
            */}
          </Providers>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
