import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// My imports
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <div>
          <Link href="/home">Home</Link>
          <br />
          <Link href="/portfolio">Portfolio</Link>
          <br />
          <Link href="/converter">Converter</Link>
          <br />
        </div>
      </body>
    </html>
  );
}
